FROM ruby:3.0.4

ENV APP_PATH /rdmapps
ENV BUNDLE_VERSION 2.2.3
ENV BUNDLE_PATH /usr/local/bundle/gems

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    nodejs npm postgresql-client python2

RUN npm install -g yarn

RUN gem install solargraph debug

RUN mkdir $APP_PATH
WORKDIR $APP_PATH

# rails server
EXPOSE 3000
# yarn server
EXPOSE 3001
# yarn server when in foreman
EXPOSE 4001

COPY scripts/dev_docker_entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/dev_docker_entrypoint.sh