FROM ruby:3.1.4

ENV APP_PATH /rdmapps
ENV BUNDLE_PATH /usr/local/bundle/gems

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    postgresql-client shared-mime-info
    
# NVM AND NODE SETUP
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION v12.22.12

RUN mkdir -p $NVM_DIR
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && nvm install $NODE_VERSION && nvm use --delete-prefix $NODE_VERSION"
ENV NODE_PATH $NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH $NODE_PATH:$PATH

# YARN SETUP
ENV YARN_VERSION 1.22.19

RUN npm install -g yarn@$YARN_VERSION

RUN mkdir $APP_PATH
WORKDIR $APP_PATH

# Install Python 2.7.9
RUN apt-get install -y \
    build-essential \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libsqlite3-dev \
    libreadline-dev \
    libffi-dev \
    wget

RUN wget https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz && \
    tar xzf Python-2.7.9.tgz && \
    cd Python-2.7.9 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    ln -s /usr/local/bin/python2.7 /usr/local/bin/python

# rails server
EXPOSE 3000
# yarn server
EXPOSE 3001
# yarn server when in foreman
EXPOSE 4001

COPY scripts/dev_docker_entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/dev_docker_entrypoint.sh
